# Generated by Django 4.2.9 on 2024-01-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_areamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaModel',
        ),
    ]
