version: '3.1'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - ./frontend:/usr/src/app
      - /app/node_modules
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:  >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: postgres:13.4
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - my-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
networks:
  my-network:
    driver: bridge
    name: my-network